### ISSUE TITLE
Adding the app to `ApplicationHelper::getClientInfo()`

### ISSUE THREAD

**Issue by mbabker** [joomla-projects/gsoc17_webservices#17]
Eventually the new application will need to be added to [`ApplicationHelper::getClientInfo()`](https://github.com/joomla-projects/gsoc17_webservices/blob/4.0-dev/libraries/src/CMS/Application/ApplicationHelper.php#L120) as that method by default loads information about all known core applications.

@wilsonge we'll need to document this as a B/C break because right now core is only reserving client ID's 0-2, and we are using ID 3 already on the downloads site, as is the new class in this repo.

(Note, I'm really only logging this so we remember there is a small B/C concern to be noted when this effort merges to core, and it's not a theoretical break 😉 )

**Comment by wilsonge** [comment]
Added to the helper with f76d440c52b87680103fd47e2c7e43794f5c9e38. Agreed we need to document the break when it goes into the main CMS
