### ISSUE TITLE
[Repo] Up-to-date synced 4.0-dev branch

### ISSUE THREAD

**Issue by zero-24** [joomla-projects/gsoc17_webservices#2]
As you are stating coding here with the 4.0-dev branche i would suggest that I include your 4.0-dev branch here in my regular update script.

This means 4.0-dev is equal to 4.0-dev from the CMS and you are not allowed to push files to that branch as this is supposed to be a exact copy of the cms one.

All changes you do can be targeted against our 4.0-dev brach which is always the synced version from the CMS.

If you agree i would reset and update the current branch to 4.0-dev periodicaly.

@muhakh @cokencorn @yvesh

**Comment by cokencorn** [comment]
I think I'm happy with that.

**Comment by zero-24** [comment]
done. your file can be found here: https://github.com/joomla-projects/gsoc17_webservices/pull/3

I have also set the 4.0 branch as default branch.
