### ISSUE TITLE
API application response

### ISSUE THREAD

**Issue by muhakh** [joomla-projects/gsoc17_webservices#8]
Implement the response of the APIs as a JDocument that takes data from extension and provides JSON response (for now).

**Comment by wilsonge** [comment]
We already have a JDocumentJson https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/joomla/document/json.php 

So this should be very similar to the existing code. It might even be worth considering adapting the existing render method in JApplicationCms to be able to deal with non-HTML responses natively

**Comment by wilsonge** [comment]
The actual body structure needs some investigation. We need to decide whether we are doing JSON API http://jsonapi.org/, JSON LD https://json-ld.org/ or one of the various other options that exist.
